### ISSUE TITLE
phone doesn't pass validation

### ISSUE THREAD

**Issue by mikeyc7m** [zipMoney/merchantapi-php#14]
i'm seeing errors where phone numbers don't pass validation, like: +61411645693
it seems to be choking on the + symbol.

looking at the code, all the preg_match checks are double-slashing the escape characters. i think this is required for java, but not for php.

**Comment by mikeyc7m** [comment]
bump!
also chokes on spaces. uh huh.

**Comment by webgig** [comment]
Hi, what version are you using? This has already been fixed in 1.0.3. 
Check here please, https://github.com/zipMoney/merchantapi-php/releases/tag/1.0.3

**Comment by mikeyc7m** [comment]
yes, i can see you have incorrectly added double slashes in 1.0.3. i'm currently on 1.0.4

**Comment by benzhangzip** [comment]
The issue have been fixed in the later version
