### ISSUE TITLE
chargesList doesn't return any transaction

### ISSUE THREAD

**Issue by ecosacandice** [zipMoney/merchantapi-php#20]
chargesList seems not return transaction
chargesRetrieve does
is that you guys stop provide "chargesList" anymore?

**Comment by benzhangzip** [comment]
Hi @ecosacandice 
This API is not implemented in our API (maybe performance issue or security issue) or token it out (beyond my time), so just ignore this API, as currently no search ability to find charges or no business demand on this features as they could search orders instead in either eCommerce system or zip merchant portal dashboard. 

Thanks and closing the old ticket.
