### ISSUE TITLE
partial capture not supported

### ISSUE THREAD

**Issue by jovanialferez** [zipMoney/merchantapi-php#23]
how do we do partial capture? (e.g. amount is less than authorized)

**Comment by benzhangzip** [comment]
There is API doc in here https://zip-online.api-docs.io/v1/api-specification/charges-retrieve-a-charge
You will need an other optional flag to indicate the amount you capture is partial capture
`{
    "amount": 50,
    "is_partial_capture": true
}`

**Comment by jovanialferez** [comment]
thanks!
